### ISSUE TITLE
No documentation apart from command line help

### ISSUE THREAD

**Issue by StevenMaude** [scraperwiki/hookbot#26]
Would be helpful if there was some guidance on how to use `hookbot`.

Particularly, I'm thinking a step-by-step guide of how to generate tokens and what environment variables I need to achieve that.

**Comment by pwaller** [comment]
I think the readme in #29 improved the situation quite a bit. I want to do a screencast as well, but first need to regain control of my https://asciinema.org account.

**Comment by pwaller** [comment]
I'm going to mark this as resolved for now since we at least have a readme.
